import { readColumn, readColumns, type Diagram } from './types';

const ident = (raw: string) =>
  raw
    .trim()
    .replace(/([a-z0-9])([A-Z])/g, '$1_$2')
    .toLowerCase()
    .replace(/[^a-z0-9_]+/g, '_')
    .replace(/_+/g, '_')
    .replace(/^_|_$/g, '') || 'unnamed';

/**
 * SQL straight from the relational diagram.
 *
 * Unlike the EER generator this performs no mapping — the diagram is already
 * a relational schema, so this is a rendering, not a translation. Tables are
 * emitted so that a table comes after everything it references, which keeps
 * the script runnable top to bottom.
 */
export function generateDdl(d: Diagram, title = 'Relational schema'): {
  sql: string;
  warnings: string[];
} {
  const warnings: string[] = [];
  const byId = new Map(d.nodes.map((n) => [n.id, n]));

  // Dependency order, with cycles broken and reported rather than looping.
  const emitted = new Set<string>();
  const ordered: typeof d.nodes = [];
  const visiting = new Set<string>();

  const visit = (id: string) => {
    if (emitted.has(id) || visiting.has(id)) return;
    visiting.add(id);
    for (const e of d.edges) {
      if (e.source === id && e.target !== id) visit(e.target);
    }
    visiting.delete(id);
    const node = byId.get(id);
    if (node && !emitted.has(id)) {
      emitted.add(id);
      ordered.push(node);
    }
  };
  for (const n of d.nodes) visit(n.id);

  const cyclic = d.nodes.filter((n) =>
    d.edges.some(
      (e) =>
        e.source === n.id &&
        d.edges.some((back) => back.source === e.target && back.target === n.id),
    ),
  );
  if (cyclic.length > 0) {
    warnings.push(
      `${cyclic.map((n) => n.name).join(', ')} reference each other in a cycle; add the foreign keys with ALTER TABLE after both exist.`,
    );
  }

  const lines: string[] = [
    `-- ${title}`,
    `-- Generated by DBMS Modeling on ${new Date().toISOString().slice(0, 10)}`,
    '-- Generic ANSI SQL; adjust types for your target database.',
    '',
  ];

  if (ordered.length === 0) lines.push('-- Nothing to generate: no tables yet.');

  for (const table of ordered) {
    const columns = readColumns(table);
    const body: string[] = [];
    const width = Math.max(0, ...columns.map((c) => ident(c.name).length));

    for (const c of columns) {
      const name = ident(c.name);
      const pad = ' '.repeat(width - name.length);
      body.push(
        `  ${name}${pad} ${c.dataType}${c.notNull || c.pk ? ' NOT NULL' : ''}${
          c.unique && !c.pk ? ' UNIQUE' : ''
        }`,
      );
    }

    const pk = columns.filter((c) => c.pk).map((c) => ident(c.name));
    if (pk.length > 0) body.push(`  PRIMARY KEY (${pk.join(', ')})`);

    for (const e of d.edges) {
      if (e.source !== table.id) continue;
      const parent = byId.get(e.target);
      if (!parent || e.columns.length === 0) continue;
      const from = e.columns
        .map((id) => readColumn(table, id)?.name)
        .filter((n): n is string => !!n)
        .map(ident);
      const to = e.references
        .map((id) => readColumn(parent, id)?.name)
        .filter((n): n is string => !!n)
        .map(ident);
      if (from.length === 0 || from.length !== to.length) continue;
      body.push(
        `  FOREIGN KEY (${from.join(', ')}) REFERENCES ${ident(parent.name)} (${to.join(', ')})${
          e.onDelete && e.onDelete !== 'NO ACTION' ? ` ON DELETE ${e.onDelete}` : ''
        }`,
      );
    }

    lines.push(`CREATE TABLE ${ident(table.name)} (`);
    lines.push(body.map((l, i) => (i === body.length - 1 ? l : `${l},`)).join('\n'));
    lines.push(');');
    lines.push('');
  }

  if (warnings.length > 0) {
    lines.push('-- ---------------------------------------------------------------');
    lines.push('-- Warnings');
    lines.push('-- ---------------------------------------------------------------');
    for (const w of warnings) lines.push(`--  ! ${w}`);
    lines.push('');
  }

  return { sql: lines.join('\n'), warnings };
}
